name: prueba

description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the build number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^5.2.1
  firebase_ui_firestore: ^1.6.4
  mailer: ^6.1.2
  bcrypt: ^1.1.3
  connectivity_plus: ^6.0.5
  image_picker: ^1.1.2
  firebase_storage: ^12.3.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  flare_flutter: ^3.0.2
  crypto: ^3.0.5
  lottie: ^3.1.2
  image_picker_web: ^4.0.0
  permission_handler: ^11.3.1
  curved_navigation_bar: ^1.0.6
  pdf: ^3.11.1
  local_auth: ^2.3.0
  url_launcher: ^6.3.0
  agora_rtc_engine: ^6.3.2
  record: ^5.1.2
  flutter_sound: ^9.16.0
  encrypt: ^5.0.3
  audioplayers: ^6.1.0
  flutter_emoji: ^2.5.1
  video_player: ^2.9.2
  location: ^6.0.2
  webview_flutter: ^4.10.0
  browser_launcher: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/BR.jpg
    - assets/images/VIAJE.jpg
    - assets/images/Colombia.png
    - assets/images/prueba.gif
    - assets/images/cat.gif
    - assets/images/cat.json
    - assets/images/travel.json
    - assets/images/qw.json
    - assets/images/plane.json

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # - images/colombia.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
